[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Wejście do labiryntu jest u szczytu schodów. Jeśli uznasz, że możemy zaczynać, prowadź.[n][uf 1 1][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10089 0 0]To będzie nasza tymczasowa baza operacyjna podczas eksploracji Tartarusa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10090 0 0]Liczę na to, że przejmiesz dowodzenie podczas operacji.[n][uf 1 1][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10091 0 0]Wygląda na to, że minęło trochę czasu, odkąd tu byliśmy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10092 0 0]Ważne, abyśmy tutaj udoskonalili nasze umiejętności bojowe, żebyśmy byli przygotowani na nagłe ataki Cieni, takie jak ten wcześniej.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10093 0 0]Zawsze warto wcześniej potrenować. Nie zapominajmy o tym.[n][uf 1 1][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10094 0 0]Jeszcze raz krótko zajmę się Tartarusem.[n][uf 1 1][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21001 0 0]Oo, [uf 4 1], ten nowy miecz wygląda nieźle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21002 0 0]Łuk, który dostałam, jest naprawdę lekki i wygląda na dość łatwy w użyciu. Nie mogę się doczekać, aż zobaczę go w akcji![n][uf 1 1][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 1 21003 0 0]Czyli przewodniczący załatwił nam wszystkim nową broń, tak? Chyba trzeba będzie mu podziękować.[n][uf 1 1][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 1 21004 0 0]Ale prawie nic nam nie wyjaśnił. Czasem nie wiem, czy bardziej nam pomaga, czy przeszkadza.[n][uf 1 1][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 21005 0 0]Wszystkie te rzeczy zostały zrobione specjalnie dla nas. Można to rozpoznać po wygrawerowanym symbolu SPOE.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 21006 0 0][uf 4 1], jak zawsze dowodzisz. I pamiętaj o sprawdzeniu sprzętu, zanim zaczniemy.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Teraz, gdy jest z nami Yamagishi, będę mogła też walczyć w pierwszym składzie.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sądzę jednak, że powinniśmy nadal wysyłać na wyprawy nie więcej niż czworo ludzi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]W ten sposób drużyna będzie działać najskuteczniej, a posiadanie rezerwy na nieprzewidziane sytuacje to zdecydowanie dobry pomysł.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Decyzję o składzie drużyny pozostawiam tobie.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Po sformowaniu tutaj drużyny możecie wyruszyć, gdy będziecie gotowi.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Zrobię, co w mojej mocy, żeby wam pomóc. Mam nadzieję, że dobrze nam pójdzie![n][uf 1 1][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Um, nie bardzo wiem, co robię, ale będę się starać ze wszystkich sił![n][uf 1 1][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10105 0 0]Wiedziałam![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10106 0 0]Te urządzenia to teleportery — portale, które są ze sobą połączone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10107 0 0]Po aktywacji można podróżować między dowolnymi innymi urządzeniami.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10108 0 0]Najważniejsze, żeby aktywować wszystkie, jakie się napotka. Przydadzą się podczas przyszłych wypraw.[n][uf 1 1][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Cieszę się, że jesteście! Wpadła mi do głowy taka myśl...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Te urządzenia to teleportery — portale, które są ze sobą połączone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Po aktywacji można podróżować między dowolnymi innymi urządzeniami.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Aktywujcie każdy napotkany teleporter. Przydadzą się podczas przyszłych wypraw.[n][uf 1 1][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Wracając do tych drzwi... prowadzą chyba do bocznej ścieżki w Tartarusie.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Krótko mówiąc, jeśli celem jest dotarcie na szczyt, ta ścieżka jest w zasadzie okrężną drogą.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Zdaje się jednak, że na tej ścieżce można znaleźć coś, co może okazać się pomocne podczas eksploracji...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]W zależności od stopnia przygotowania może być warto zajrzeć za te drzwi.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Jesteście! Zdaje się, że udało wam się uratować zaginioną osobę...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Na razie może tu zostać. W odpowiednim czasie ją stąd zabierzemy.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Jesteście! Kamień spadł mi z serca, gdy udało wam się uratować tego kotka![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Może tu na razie zostać. W odpowiednim czasie bezpiecznie go stąd zabierzemy.[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], czy mogę zająć ci chwilę?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]W Tartarusie pojawił się dziś wyjątkowy mały gość...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Trzymał w zębach fragment świecący dziwnym niebieskim światłem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Jeśli dręczy cię ciekawość, może warto złożyć temu gościowi wizytę.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Według mnie może się pojawić na [uf 2 4 0]. piętrze. Nie zatrzymuję cię...[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], czy mogę zająć ci chwilę?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]W Tartarusie pojawili się dziś wyjątkowi mali goście...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Cóż za szczególna nagroda... Jeśli dręczy cię ciekawość, może warto złożyć temu gościowi wizytę.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Może w przyszłości pojawi się więcej tych dziwnych, świecących fragmentów![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Według mnie mogą się pojawić na piętrach [uf 2 4 0]. i [uf 2 4 1]. Nie zatrzymuję cię...[n][uf 1 1][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]O, proszę, proszę, co my tu mamy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Zdaje się, że w tej chwili masz bardzo dużo Person.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Muszę przyznać, że to imponujące. Jednakże...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Być może w obecnym stanie jesteś w stanie korzystać z jeszcze potężniejszych Person.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Możesz udać się do Aksamitnego Pokoju, kiedy tylko zechcesz.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4017 0 0]O, wróciliście. Dobrze. Bezpieczeństwo wszystkich jest najważniejsze.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Mam tu przedmioty znalezione podczas zwiadu przez innych członków ekipy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Dam je wam.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Decyzja o tym, kiedy wrócić, należy do ciebie jako naszego dowódcy, ale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0]Zostawianie towarzyszy po drodze jest nieeleganckie. Należy ich później przeprosić.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Miło was znów widzieć! Cieszę się, że jesteście cali.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Przechowałam przedmioty znalezione przez innych podczas wypraw...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Przekażę je wam.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Hm, wiem, że to pewnie nie problem, ale jak ludzie idą na zwiad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Niedobrze jest po powrocie nie zamienić z nimi choć słowa... Gdyby mnie się to przydarzyło, poczułabym się osamotniona.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]A, za pamięci, jeśli chcecie eksplorować dalej...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Dam wam przedmioty znalezione przez innych podczas wypraw.[n][uf 1 1][e]

[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] reaguje...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]kartę Wielkich Arkanów Kapłanki.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]kartę Wielkich Arkanów Eremity.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]kartę Wielkich Arkanów Wisielca.[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] i [uf 4 4 1 0 1 1] reagują...[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]karty Wielkich Arkanów Cesarzowej i Cesarza.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]karty Wielkich Arkanów Kapłana i Kochanków.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]karty Wielkich Arkanów Rydwanu i Sprawiedliwości.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]Do przetasowania dodano[n]karty Wielkich Arkanów Koła Fortuny i Siły.[n][uf 1 1][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Czekałam na ciebie. Czy mogę zająć ci chwilę?[n][uf 1 1][e]

[msg MND_ArcanaInfo02]
[uf 0 5 65278][uf 2 1]Karta Kochanków świeci...[n][uf 1 1][e]

[msg SYS_ArcanaInfo]
[uf 0 5 65278][uf 2 1]Po zdobyciu karty Kochankowie[n]premie do fuzji zapewniane przez więzi[n]zwiększają się.[n][uf 1 1][e]

[msg SYS_TutoAfter_TheurgiaGa]
[uf 0 5 65278][uf 2 1]Dodano [uf 0 1 2]teurgię[uf 0 1 27] do samouczków.[n][uf 1 1][e]

[msg SYS_TutoAfter_PartyMembe]
[uf 0 5 65278][uf 2 1]Dodano [uf 0 1 2]zmianę formacji drużyny[uf 0 1 27] do samouczków.[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Ponownie przeprowadziłam wyszukiwanie, ale nadal nie wykrywam w środku nikogo więcej.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Uratowaliśmy już chyba wszystkie osoby, które przypadkiem znalazły się w Tartarusie.[n][uf 1 1][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Czy nikomu nic nie jest?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Na chwilę straciłam z wami kontakt... A później tak jakby teleportowało was tutaj.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Cóż za dziwne miejsce... Jak myślisz, o co chodzi z tym zegarem?[n][uf 1 1][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[uf 0 5 65278][uf 2 1]To nam się chyba może przydać...[e]
[uf 0 5 65278][uf 2 1]Nie mam pojęcia.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]To się chyba przyda. Warto będzie z tego korzystać.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Nie wygląda na niebezpieczny... Może wywiera na wszystkich pozytywne skutki.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Jeśli wejście znów się otworzy, wypróbujmy je![n][uf 1 1][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Fajnie, że już jesteś! I jak podobał ci się zegar tym razem?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Hej, chwila...[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]O, jeszcze ja![n][uf 1 1][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]W tej chwili czuję się w sumie całkiem nieźle... Jeśli pozwolisz, chciałabym się przyłączyć.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Hej, [uf 4 2]...[n][uf 1 1][e]

[msg MSG_060_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ja też, ja też![n][uf 1 1][e]

[msg MSG_060_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Czuję, jak rozpiera mnie energia. Weźmiesz mnie do drużyny?[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Chwileczkę...[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ja też poproszę.[n][uf 1 1][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Mam już solidne wyobrażenie o tym, jak powinienem się poruszać. Pozwól mi dołączyć do drużyny, a nie pożałujesz.[n][uf 1 1][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Przepraszam, wybacz...[n][uf 1 1][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]A... w zasadzie myślę podobnie.[n][uf 1 1][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Mam przeczucie, że poradzę sobie teraz wyjątkowo dobrze. Możesz wziąć mnie do drużyny?[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Może to trochę niespodziewane, ale...[n][uf 1 1][e]

[msg MSG_064_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Mnie również to dotyczy.[n][uf 1 1][e]

[msg MSG_064_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Jestem wyjątkowo pełna energii. Wyznacz mnie proszę do walki na pierwszej linii.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 1], chciałbym prosić...[n][uf 1 1][e]

[msg MSG_065_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]O, jeszcze ja![n][uf 1 1][e]

[msg MSG_065_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Mógłbyś wystawić mnie w pierwszej linii? Czuję, że mogę stać się dużo silniejszy.[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Hau![n][uf 1 1][e]

[msg MSG_066_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*Skomle*[n][uf 1 1][e]

[msg MSG_066_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Hau, hau! Hau![n][uf 1 1][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Hej, zaczekaj.[n][uf 1 1][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Przepraszam, że się wtrącam, ale też chcę się przyłączyć.[n][uf 1 1][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Możesz wziąć mnie do ekipy? W tej chwili czuję się całkiem dobrze.[n][uf 1 1][e]

[msg MSG_064_7_0_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Mam przeczucie, że moja moc się zwiększy. Możesz wyznaczyć mnie na pierwszą linię?[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]A, racja... chciałam ci coś powiedzieć.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Wygląda na to, że Koro ma w sumie dwie teurgie![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Przewodniczący dowiedział się tego, badając jego możliwości.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Nie bardzo wiemy, dlaczego tak jest, ale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Miło, że jest po naszej stronie.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Chyba warto mieć to na uwadze podczas tworzenia drużyny. To by było na tyle![n][uf 1 1][e]

[msg MND_Tuto_MissingNPC_0]
[uf 0 5 65278][uf 2 1]Jak się zastanowić...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Elizabeth wspominała o „gościach”[n]zaglądających do Tartarusa...[n][uf 1 1][e]

