[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Der Eingang zum Labyrinth befindet sich am oberen Ende der Treppe. Wenn du bereit bist, geh voraus.[n][uf 1 1][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10089 0 0]Wenn wir den Tartarus erkunden, ist das hier unsere vorläufige Operationsbasis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10090 0 0]Ich zähle darauf, dass du den Einsatz leitest.[n][uf 1 1][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10091 0 0]Es ist wohl schon eine Weile her, dass wir hier waren ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10092 0 0]Wir müssen unsere Kampffähigkeiten schulen, damit wir auf plötzliche Schattenangriffe gefasst sind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10093 0 0]Es schadet nie, sich durch gutes Training vorzubereiten. Das musst du beherzigen.[n][uf 1 1][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10094 0 0]Ich erkläre dir den Tartarus noch mal.[n][uf 1 1][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21001 0 0]Ooh, [uf 4 1]-kun, dieses neue Schwert sieht echt cool aus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21002 0 0]Dieser Bogen ist ziemlich leicht und flexibel einsetzbar. Ich will ihn unbedingt ausprobieren![n][uf 1 1][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 1 21003 0 0]Shuji hat uns also neue Waffen besorgt. Wir sollten uns bei ihm bedanken.[n][uf 1 1][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 1 21004 0 0]Allerdings hat er nichts erklärt. Manchmal bin ich nicht sicher, ob er wirklich eine Hilfe ist.[n][uf 1 1][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 21005 0 0]An der S.E.E.S.-Gravur sieht man, dass alles maßgefertigt ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 21006 0 0]Du gibst wie immer die Befehle, [uf 4 1]. Und überprüfe deine Ausrüstung, bevor es losgeht.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Jetzt, wo wir Yamagishi haben, stehe ich auch für den Einsatz an der Front zur Verfügung.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich denke jedoch, wir sollten weiterhin maximal zu viert auf Erkundungstour gehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Das garantiert eine effiziente Zusammenarbeit. Und es ist ratsam, Reservisten in der Hinterhand zu haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Was die Zusammensetzung der Gruppe angeht, das überlasse ich ganz dir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sobald du hier eine Gruppe zusammengestellt und dich vorbereitet hast, kannst du aufbrechen.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Ich gebe mein Bestes, euch allen zu helfen. Hoffentlich läuft es gut![n][uf 1 1][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Ähm, ich weiß zwar nicht genau, was ich mache, aber ich gebe mein Bestes![n][uf 1 1][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10105 0 0]Ich wusste es![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10106 0 0]Diese Geräte sind Teleporter – Portale, die miteinander verbunden sind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10107 0 0]Wenn sie einmal aktiviert sind, kannst du zwischen diesen Geräten beliebig hin und her reisen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10108 0 0]Aktiviere also alle, die du findest. Sie sind für zukünftige Erkundungen extrem nützlich.[n][uf 1 1][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Willkommen zurück! Es ist tatsächlich wie gedacht ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Diese Geräte sind Teleporter – Portale, die miteinander verbunden sind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Wenn sie einmal aktiviert sind, kannst du zwischen diesen Geräten beliebig hin und her reisen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Bitte aktiviere also alle, die du findest. Sie sind für zukünftige Erkundungen sehr nützlich.[n][uf 1 1][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Was die Tür angeht ... sie scheint zu einem Nebenpfad im Tartarus zu führen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Kurz gesagt, wenn du nach oben gehst, würde dieser Pfad als eine Art Umweg gelten.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Allerdings findest du dort vermutlich etwas, was sich als hilfreich erweisen könnte ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Je nachdem, wie gut du vorbereitet bist, könnte es sich lohnen, diese Türen zu betreten.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Willkommen zurück! Du konntest also eine vermisste Person retten ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Sie kann erst einmal hierbleiben – wir bringen sie nach Hause, sobald es möglich ist.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Willkommen zurück! Ich bin so froh, dass du die Katze gerettet hast![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Sie kann vorerst hierbleiben – wir bringen sie in Sicherheit, sobald es möglich ist.[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], hast du einen Augenblick Zeit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Der Tartarus hat heute offenbar einen kleinen Ehrengast ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Und zwischen seinen Zähnen hält er ein Fragment, das ein eigenartiges blaues Licht ausstrahlt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Sollte dich die Neugier übermannen, statte diesem Gast doch einen Besuch ab.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Er ist vermutlich auf Ebene [uf 2 4 0]. Also, husch ...[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], hast du einen Augenblick Zeit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Der Tartarus hat heute offenbar ein paar kleine Ehrengäste ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Was für ein Glücksfall für dich. Sollte dich die Neugier übermannen, statte diesem Gast doch einen Besuch ab.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Vielleicht finden sich in deiner Zukunft noch mehr von diesen eigenartigen leuchtenden Fragmenten![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Sie sind vermutlich auf den Ebenen [uf 2 4 0] und [uf 2 4 1]. Also, husch ...[n][uf 1 1][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Oh? Was haben wir denn hier?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Du scheinst im Augenblick eine große Anzahl an Personas zu besitzen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Sehr beeindruckend, muss ich sagen. Allerdings ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Vielleicht kannst du in deinem aktuellen Zustand sogar noch mächtigere Personas einsetzen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Sollte dir der Sinn danach stehen, begib dich bitte in den Velvet Room.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4017 0 0]Ah, du bist zurück. Gut. Eure Sicherheit ist wichtiger als alles andere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe, was die anderen Gruppenmitglieder gefunden haben ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Darf ich es dir übergeben?[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Es liegt natürlich an dir, wann du entscheidest, zurückzukehren, doch ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0]Deine Kameraden zurückzulassen, gehört sich nicht. Du bist ihnen eine anständige Entschuldigung schuldig.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Willkommen zurück. Schön, dass es allen gut geht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ich habe alles, was die anderen während der Erkundung gefunden haben ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ich händige es dir jetzt aus.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Ähm, ich weiß, es stört sie vermutlich nicht, aber wenn jemand gerade zum Auskundschaften fort ist ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Dann ist es nicht nett, einfach zurückzukehren, ohne ihm Bescheid zu sagen. Ich würde mich dann einsam fühlen.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, bevor ich es vergesse ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ich gebe dir noch, was die anderen bei der Erkundung gefunden haben.[n][uf 1 1][e]

[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 1 0]" zeigt eine Reaktion ...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte Hohepriesterin[n]wurde zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Eremit"[n]wurde zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Gehängter"[n]wurde zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] und [uf 4 4 1 0 1 1] reagieren ...[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karten "Herrscherin" und "Herrscher"[n]wurden zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karten "Hierophant" und "Liebende"[n]wurden zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karten "Wagen" und "Gerechtigkeit"[n]wurden zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karten "Fortuna" und "Stärke"[n]wurden zur Shuffle Time hinzugefügt.[n][uf 1 1][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Ich habe schon auf dich gewartet. Darf ich einen Augenblick deiner Zeit beanspruchen?[n][uf 1 1][e]

[msg MND_ArcanaInfo02]
[uf 0 5 65278][uf 2 1]Die Liebende-Karte leuchtet ...[n][uf 1 1][e]

[msg SYS_ArcanaInfo]
[uf 0 5 65278][uf 2 1]Mit Erhalt der Liebenden[n]erhöht sich Social Link-Bonus[n]während der Fusion.[n][uf 1 1][e]

[msg SYS_TutoAfter_TheurgiaGa]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Theurgie[uf 0 1 27] wurde zu den Tutorials hinzugefügt.[n][uf 1 1][e]

[msg SYS_TutoAfter_PartyMembe]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Ändern der Gruppenzusammenstellung[uf 0 1 27] wurde zu den Tutorials hinzugefügt.[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Ich habe es mit einer weiteren Suche probiert, aber ich kann noch immer niemanden drinnen entdecken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Es scheint, als hätten wir jeden gerettet, der versehentlich im Tartarus gelandet ist.[n][uf 1 1][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Geht es allen gut?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Für einen Moment hatte ich euch alle verloren ... aber dann war es, als hättet ihr euch hierher teleportiert.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ein merkwürdiger Ort ... Was hat es wohl mit dieser Uhr auf sich?[n][uf 1 1][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[uf 0 5 65278][uf 2 1]Scheint, als könnten wir es gebrauchen ...[e]
[uf 0 5 65278][uf 2 1]Keine Ahnung.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Wenn es hilfreich zu sein scheint, wäre es klug von uns, es zu nutzen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Sie wirkt nicht gefährlich ... vielleicht hat sie sogar einen positiven Effekt auf alle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Wenn der Eingang sich noch einmal öffnet, probieren wir es aus![n][uf 1 1][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Willkommen zurück! Wie hat dir die Uhr diesmal gefallen?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Hey, Moment kurz ...[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oh, ich auch![n][uf 1 1][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Mir geht es eigentlich gerade ziemlich gut. Wenn es in Ordnung ist, würde ich mich gerne anschließen.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Hey, [uf 4 2] ...[n][uf 1 1][e]

[msg MSG_060_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ich will auch mal![n][uf 1 1][e]

[msg MSG_060_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ich bin gerade so richtig voller Energie. Kann ich der Gruppe beitreten?[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Warte kurz ...[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ah, ebenso.[n][uf 1 1][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ich habe ein richtig gutes mentales Bild, wie ich mich bewegen muss. Lass mich mitmachen, du wirst es nicht bereuen.[n][uf 1 1][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Entschuldigung, Verzeihung ...[n][uf 1 1][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Oh, mir geht es ganz ähnlich.[n][uf 1 1][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Ich habe das Gefühl, dass ich gerade jetzt eine große Hilfe wäre. Nimmst du mich bitte in deine Gruppe auf?[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Das kommt vielleicht etwas plötzlich, aber ...[n][uf 1 1][e]

[msg MSG_064_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Das gilt auch für mich.[n][uf 1 1][e]

[msg MSG_064_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Ich bin ungewöhnlich energiegeladen – bitte nimm mich mit an die Front.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 1]-san, ich wollte dich fragen ...[n][uf 1 1][e]

[msg MSG_065_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Oh, ich auch![n][uf 1 1][e]

[msg MSG_065_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Nimmst du mich bitte mit an die Front? Ich habe das Gefühl, dass ich viel stärker werden kann.[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Rawuff![n][uf 1 1][e]

[msg MSG_066_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*winsel*[n][uf 1 1][e]

[msg MSG_066_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Rawuff, rawuff! Rawuff![n][uf 1 1][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Hey, warte mal kurz.[n][uf 1 1][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Sorry, dass ich so dazwischenplatze, aber geht mir auch so.[n][uf 1 1][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Kannst du mich mitnehmen? Ich fühle mich gerade echt ziemlich gut.[n][uf 1 1][e]

[msg MSG_064_7_0_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Ich habe das Gefühl, dass meine Kraft sich verstärkt. Kannst du mich bitte in deine Gruppe aufnehmen?[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Ah, stimmt ... ich wollte dir ja noch etwas sagen ...[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Koro-chan hat anscheinend sogar zwei Theurgien![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Der Vorsitzende hat das festgestellt, indem er sein Potenzial erforscht hat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Wir wissen nicht genau, warum das der Fall ist, aber ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Es ist definitiv gut, ihn auf unserer Seite zu haben.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Behalte das bitte einfach im Kopf, wenn du eine Gruppe zusammenstellst. Das ist alles![n][uf 1 1][e]

[msg MND_Tuto_MissingNPC_0]
[uf 0 5 65278][uf 2 1]Da fällt mir ein ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Elizabeth hatte erwähnt, dass "Gäste" in den Tartarus wandern ...[n][uf 1 1][e]

