[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]A entrada do labirinto é no andar de cima. Quando estiver pronto para começar, vá na frente.[n][uf 1 1][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10089 0 0]Conforme exploramos o Tártaro, essa será nossa base temporária de operações.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10090 0 0]Estou contando com você para assumir o comando durante a operação.[n][uf 1 1][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10091 0 0]Parece que já faz um tempo desde a última vez que viemos aqui...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10092 0 0]É importante aprimorarmos nossas habilidades de combate para estarmos preparados para ataques-surpresa de Sombras, como o que enfrentamos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10093 0 0]Treinar de antemão nunca é demais. Mantenha isso em mente.[n][uf 1 1][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10094 0 0]Vou explicar rapidamente sobre o Tártaro mais uma vez.[n][uf 1 1][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21001 0 0]Ah, [uf 4 1]-kun, essa nova espada é bem bacana.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21002 0 0]Esse arco que ganhei é muito leve e parece bem fácil de manejar. Mal posso esperar pra usar![n][uf 1 1][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 1 21003 0 0]Então o presidente providenciou armas novas pra todos nós? A gente devia agradecer.[n][uf 1 1][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 1 21004 0 0]Ele nem explicou direito. Às vezes não sei se ele tá mesmo ajudando ou não.[n][uf 1 1][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 21005 0 0]Tudo feito sob medida para nós. Dá pra ver pela marca "SEES" gravada em todas as peças.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 21006 0 0]Você está no comando como sempre, [uf 4 1]. E não deixe de conferir o equipamento antes de começarmos.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Agora que temos a Yamagishi, também vou estar disponível para a linha de frente.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Porém, acho que você deve continuar indo em grupos de quatro no máximo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]A equipe ficaria mais coesa, e seria sensato ter reservas em caso de imprevistos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Quanto aos membros a incluir, deixo a decisão com você.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Depois de formar um grupo com os membros aqui, você pode ir quando quiser.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Vou dar muito duro pra ajudar vocês. Espero que tudo corra bem![n][uf 1 1][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Hum, eu não sei exatamente o que tô fazendo, mas vou tentar o meu melhor![n][uf 1 1][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10105 0 0]Eu sabia![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10106 0 0]Esses dispositivos são teletransportadores. Portais que estão conectados uns aos outros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10107 0 0]Uma vez ativados, você poderá viajar para qualquer outro dispositivo conectado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10108 0 0]Certifique-se de ativar qualquer um que você encontrar. Eles serão bem úteis em futuras expedições.[n][uf 1 1][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bem-vindo de volta! É como eu imaginava mesmo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Esses dispositivos são teletransportadores. Portais que estão conectados uns aos outros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Uma vez ativados, você poderá viajar para qualquer outro dispositivo conectado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Não deixe de ativar todos que encontrar. Eles serão bem úteis em futuras expedições.[n][uf 1 1][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Sobre essa porta, parece que ela dá em outro caminho do Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ou seja, para quem quer subir, seria um desvio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Porém, parece que você vai conseguir uma coisa nesse caminho que pode ajudar na exploração...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Dependendo do seu nível de preparo, pode valer a pena tentar.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Bem-vindo de volta! Então quer dizer que você conseguiu resgatar uma pessoa desaparecida...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ela pode ficar aqui por enquanto. Quando for o momento, levamos para um lugar seguro.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bem-vindo de volta! Tô tão aliviada de você ter conseguido salvar o gatinho![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ele pode ficar aqui por enquanto. Quando for o momento, levamos para um lugar seguro.[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], posso falar com você um instante?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]O Tártaro tem um convidado especial hoje...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]E, na boca, ele trouxe uma lasca que emite uma luz azul intrigante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Se a sua curiosidade falar mais alto, talvez valha a pena procurar esse convidado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Creio que está no andar [uf 2 4 0]. Pronto, pode ir...[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], posso falar com você um instante?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]O Tártaro tem convidados especiais hoje...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Que surpresa agradável para você... Se a sua curiosidade falar mais alto, talvez valha a pena procurar esse convidado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Talvez no futuro você encontre mais daquelas lascas brilhosas e intrigantes![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Creio que estão nos andares [uf 2 4 0] e [uf 2 4 1]. Pronto, pode ir...[n][uf 1 1][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Ora, ora, o que temos aqui?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Você possui um grande número de Personas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Impressionante, eu diria... Porém...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Será que, no seu estado atual, você não poderia utilizar Personas ainda mais poderosas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Se esse for o seu desejo, dirija-se à Sala de Veludo.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4017 0 0]Ah, vocês voltaram. Ótimo, a segurança de todos é o mais importante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Eu estou com os itens que os nossos colegas acharam durante o reconhecimento...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Vou deixá-los com você.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Agora, como líder, você decide quando voltar, mas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0]Não é de bom-tom deixar nossos camaradas para trás. Você deve desculpas.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bem-vindos de volta! Fico feliz que todos tenham voltado bem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Estou com os itens que o pessoal achou.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Vou deixar com você.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Hum, eu sei que eles não devem se incomodar com isso, mas, quando estão vasculhando...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Não é legal voltar direto sem falar com eles... Eu me sentiria sozinha se fosse comigo.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, se você vai voltar a explorar, antes que eu me esqueça...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Vou deixar com você o que o pessoal achou.[n][uf 1 1][e]

[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] está reagindo...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]A carta da Sacerdotisa[n]foi adicionada à Hora das Cartas.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]A carta do Eremita[n]foi adicionada à Hora das Cartas.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]A carta do Enforcado[n]foi adicionada à Hora das Cartas.[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] e [uf 4 4 1 0 1 1] estão reagindo...[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]As cartas da Imperatriz e do Imperador[n]foram adicionadas à Hora das Cartas.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]As cartas do Hierofante e dos Enamorados[n]foram adicionadas à Hora das Cartas.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]As cartas do Carro e da Justiça[n]foram adicionadas à Hora das Cartas.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]As cartas da Fortuna e da Força[n]foram adicionadas à Hora das Cartas.[n][uf 1 1][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Eu estava à sua espera. Posso falar com você um segundinho?[n][uf 1 1][e]

[msg MND_ArcanaInfo02]
[uf 0 5 65278][uf 2 1]A carta dos Enamorados está brilhando...[n][uf 1 1][e]

[msg SYS_ArcanaInfo]
[uf 0 5 65278][uf 2 1]Ao obter os Enamorados,[n]o bônus de Vínculo Social[n]nas fusões aumenta.[n][uf 1 1][e]

[msg SYS_TutoAfter_TheurgiaGa]
[uf 0 5 65278][uf 2 1]A [uf 0 1 2]Teurgia[uf 0 1 27] foi adicionada aos Tutoriais.[n][uf 1 1][e]

[msg SYS_TutoAfter_PartyMembe]
[uf 0 5 65278][uf 2 1]A [uf 0 1 2]Mudança da Formação do Grupo[uf 0 1 27] foi adicionada aos Tutoriais.[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Tentei fazer outra busca, mas não detectei a presença de mais ninguém.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Acho que já resgatamos todo mundo que foi parar no Tártaro.[n][uf 1 1][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Estão todos bem?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Por um instante, eu perdi vocês todos... Mas aí do nada vocês se teletransportaram pra cá.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Que lugar esquisito... O que você acha que esse relógio pode ser?[n][uf 1 1][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[uf 0 5 65278][uf 2 1]Acho que a gente pode usar...[e]
[uf 0 5 65278][uf 2 1]Não faço ideia.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Se parecer útil, seria bom a gente usar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Não parece perigoso... Vai ver que tem um efeito positivo no pessoal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Se a entrada se abrir de novo, vamos testar![n][uf 1 1][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bem-vindo de volta! Como foi no relógio?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ei, peraí...[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Eu também![n][uf 1 1][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Tô me sentindo ótima. Se não for problema, queria ir junto.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ei, [uf 4 2]...[n][uf 1 1][e]

[msg MSG_060_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Eu também, eu também![n][uf 1 1][e]

[msg MSG_060_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Tô transbordando de energia. Não quer me botar no grupo?[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Espera um segundo...[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ah, idem.[n][uf 1 1][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Tenho uma noção bem clara do que fazer. Se você me deixar ir junto, não vai se arrepender.[n][uf 1 1][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Com licença...[n][uf 1 1][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Ah, é como eu me sinto também.[n][uf 1 1][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Algo me diz que eu vou me sair especialmente bem hoje. Poderia me incluir no seu grupo?[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Então, talvez seja meio repentino, mas...[n][uf 1 1][e]

[msg MSG_064_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Isso também se aplica amim.[n][uf 1 1][e]

[msg MSG_064_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Estou especialmente cheia de energia. Por favor, me ponha na linha de frente.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 1]-san, eu queria perguntar...[n][uf 1 1][e]

[msg MSG_065_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Eu também![n][uf 1 1][e]

[msg MSG_065_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Você podia me botar na linha de frente? Sinto que agora eu posso ficar bem mais forte.[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

[msg MSG_066_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*ganido*[n][uf 1 1][e]

[msg MSG_066_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Au, au! Au![n][uf 1 1][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Ei, espera um segundo.[n][uf 1 1][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Desculpa me meter, mas eu também.[n][uf 1 1][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Pode me incluir? Tô me sentindo ótimo.[n][uf 1 1][e]

[msg MSG_064_7_0_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Sinto que o meu poder vai ser amplificado. Você poderia me incluir na linha de frente?[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Ah, é! Tenho uma coisa pra contar...[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]O Koro-chan tem duas teurgias![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]O presidente descobriu isso pesquisando o potencial dele.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ainda não sabemos o motivo, mas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]É muito bom poder contar com ele.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Acho que seria bom levar em conta na hora de montar o grupo. Só isso![n][uf 1 1][e]

[msg MND_Tuto_MissingNPC_0]
[uf 0 5 65278][uf 2 1]Pensando bem...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A Elizabeth mencionou "convidados"[n]no Tártaro...[n][uf 1 1][e]

