[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Labirentin girişi, merdivenlerin en tepesinde. Başlamaya hazır hissettiğinde yolu göster.[n][uf 1 1][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10089 0 0]Burası Tartarus'u keşfederken geçici operasyon üssümüz olacak.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10090 0 0]Operasyon sırasında sorumluluk alacağına güveniyorum.[n][uf 1 1][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10091 0 0]Buraya geleli epey uzun zaman olmuş gibi sanki...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10092 0 0]Önceki gibi ani Gölge saldırılarına karşı hazırlıklı olabilmek için muharebe becerilerimizi daha da geliştirmemiz gerek.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10093 0 0]Önceden talim yapmak her zaman iyidir. Bunu aklında tutmaya çalış.[n][uf 1 1][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10094 0 0]Tartarus hakkında bir kez daha kısaca bilgi vereceğim.[n][uf 1 1][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21001 0 0]Ooo, [uf 4 1]-kun, o yeni kılıç epey havalı görünüyor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21002 0 0]Bendeki bu yay çok hafif ve kullanımı kolay gibi görünüyor. İş üstünde görmek için sabırsızlanıyorum![n][uf 1 1][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 1 21003 0 0]Demek Başkan hepimize yeni silahlar da aldı, ha? Bence ona teşekkür etmeliyiz.[n][uf 1 1][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 1 21004 0 0]Gerçi neredeyse hiçbir şeyi açıklamadı. Bazen gerçekten faydalı olup olmadığını anlayamıyorum.[n][uf 1 1][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 21005 0 0]Bunların hepsi bize özel yapıldı. Her şeyin üzerindeki UMDİB işaretinden anlayabilirsiniz.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 21006 0 0]Her zamanki gibi komuta sende [uf 4 1]. Başlamadan önce ekipmanını kontrol etmeyi de unutma.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Yamagishi de burada olduğuna göre, ön cephelere ben de katılabilirim.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Yine de gezilere en fazla dört kişi göndermeye devam etmemiz gerektiğini düşünüyorum.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bu çok uyumlu bir ekip oluşturur ve beklenmedik durumlar için yedek üyeler olması da akıllıca olur.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Takıma kimleri alacağın konusunu sana bırakıyorum.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Buradaki üyelerle bir takım oluşturduğunda harekete geçebiliriz.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Size yardım etmek için elimden gelenin en iyisini yapacağım. Umarım her şey iyi gider![n][uf 1 1][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Ne yaptığımı tam olarak bilmiyorum ama elimden geleni yapacağım![n][uf 1 1][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10105 0 0]Biliyordum![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10106 0 0]Bu cihazlar ışınlayıcı... Her biri diğerine bağlı birer portal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10107 0 0]Etkinleştirdiğin zaman diğer cihazlar arasında yolculuk edebileceksin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10108 0 0]Karşına çıktıkça etkinleştirmeye çalış. Gelecekteki keşiflerde çok işe yarayacaklar.[n][uf 1 1][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Tekrar hoş geldin! Tıpkı düşündüğüm gibi...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Bu cihazlar ışınlayıcı... Her biri diğerine bağlı birer portal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Etkinleştirdiğin zaman diğer cihazlar arasında yolculuk edebileceksin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Karşına çıktıkça etkinleştir lütfen. Gelecekteki keşiflerde çok işe yarayacaklar.[n][uf 1 1][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]O kapı, Tartarus'taki bir yan yola açılıyormuş gibi görünüyor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Kısacası, yukarı çıkıyorsan o yoldan gitmek yolu uzatmana sebep olacak.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ancak o yoldan gidersen keşfe yardımcı olacak bir şey elde edebilirmişsin gibi görünüyor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ne kadar hazır olduğuna bağlı olarak bu kapıları denemek iyi bir fikir olabilir.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Tekrar hoş geldin! Görünüşe göre kayıp bir kişiyi kurtarmışsın...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Şimdilik burada kalabilir... Zamanı geldiğinde onu yollarız.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Tekrar hoş geldin! O kediciği kurtarabilmene o kadar sevindim ki![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Şimdilik burada kalabilir... Zamanı geldiğinde onu güvenli bir yere yollarız.[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0]Bir saniyeni ayırır mısın [uf 4 2]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Tartarus'un bugün özel bir konuğu varmış gibi görünüyor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Çenesinin arasında garip bir mavi ışık yayan bir parçayı sıkıca tutuyor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Merakına yenilirsen belki de bu konuğu ziyaret etmen en iyisi olur.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Muhtemelen [uf 2 4 0]. katta olacaktır. Tamam, git bakalım...[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0]Bir saniyeni ayırır mısın [uf 4 2]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Tartarus'un bugün bazı özel konukları varmış gibi görünüyor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Senin için ne nadir bir şey... Merakına yenilirsen belki de bu konuğu ziyaret etmen en iyisi olur.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Belki de geleceğinde bu tuhaf, parlak parçalardan daha çok vardır![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 2 4 0]. ve [uf 2 4 1]. katta olmaları daha olası. Tamam, gidin bakalım...[n][uf 1 1][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Vay vay, ne varmış burada?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Şu an çok fazla sayıda Personaya sahipsin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Bunun epey etkileyici olduğunu söylemeliyim. Bununla birlikte...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Belki mevcut durumunda çok daha güçlü Personalar da kullanabilirsin, ne dersin?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Bu ilgini çekerse Kadife Odaya git lütfen.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4017 0 0]Dönmüşsün. Güzel... Herkesin güvende olması, geri kalan her şeyden daha önemli.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Diğer ekip arkadaşlarımızın keşifleri sırasında buldukları öğeler bende...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Onları sana teslim etmeme izin ver.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Ne zaman döneceğin sana kalmış, sonuçta lidersin. Ama...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0]Yoldaşlarını arkada bırakmak yakışık almıyor. Onlara bir özür borçlusun.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Tekrar hoş geldiniz! Güvende olmanıza sevindim.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Diğerlerinin bulduğu öğeleri tutuyorum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Onları sana teslim edeceğim.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Şey... Bu onları rahatsız etmez muhtemelen ama insanlar keşifteyken...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Onlara bir şey demeden öylece geri dönmek hoş değil... Bu bana olsa çok yalnız hissederdim.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, keşfe dönmeden önce unutmadan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Diğerlerinin bulduklarını sana teslim edeyim.[n][uf 1 1][e]

[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] tepki veriyor...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]Azize Büyük Arkana kartı[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]Ermiş Büyük Arkana kartı[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]Asılan Adam Büyük Arkana kartı[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] ve [uf 4 4 1 0 1 1] tepki veriyor...[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]İmparator ve İmparatoriçe Büyük Arkana kartları[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]Aziz ve Aşıklar Büyük Arkana kartları[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]Araba ve Adalet Büyük Arkana kartları[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]Kader Çarkı ve Güç Büyük Arkana kartları[n]Karıştırma Zamanına eklendi.[n][uf 1 1][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Seni bekliyordum. Bir saniyeni ayırır mısın?[n][uf 1 1][e]

[msg MND_ArcanaInfo02]
[uf 0 5 65278][uf 2 1]Aşıklar kartı parlıyor...[n][uf 1 1][e]

[msg SYS_ArcanaInfo]
[uf 0 5 65278][uf 2 1]Aşıklar kartını aldıktan sonra[n]birleştirme esnasındaki[n]Sosyal Bağ bonusu artar.[n][uf 1 1][e]

[msg SYS_TutoAfter_TheurgiaGa]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Teürji[uf 0 1 27], Eğitimlere eklendi.[n][uf 1 1][e]

[msg SYS_TutoAfter_PartyMembe]
[uf 0 5 65278][uf 2 1][uf 0 1 2]Takım Dizilişini Değiştirme[uf 0 1 27] Eğitimlere eklendi.[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Farklı bir şekilde aramayı denedim ama hâlâ içeride başka birinin varlığını algılamıyorum.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Bir şekilde kendini Tartarus'ta bulmuş olan herkesi kurtardık galiba.[n][uf 1 1][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Herkes iyi mi?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Bir saniyeliğine hepinizi kaybettim... Ama sonra birden buraya ışınlanmışsınız gibi oldu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ne garip bir yer... O saatin olayı ne olabilir sence?[n][uf 1 1][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[uf 0 5 65278][uf 2 1]Bunu kullanabiliriz gibi duruyor...[e]
[uf 0 5 65278][uf 2 1]Bilmiyorum.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]İşe yarar gibi görünüyor. Bunu kullanmamız akıllıca olacaktır.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Tehlikeli gibi görünmüyor... Belki herkesin üzerinde olumlu bir etkisi vardır...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Giriş tekrar açılırsa deneyelim![n][uf 1 1][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Tekrar hoş geldin. Bu sefer saat nasıldı?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Bir saniye...[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Aa, ben de![n][uf 1 1][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Aslında şu an çok iyi hissediyorum. Senin için bir sakıncası yoksa sana katılmak isterim.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Hey [uf 4 2]...[n][uf 1 1][e]

[msg MSG_060_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ben de, ben de![n][uf 1 1][e]

[msg MSG_060_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Enerji doluyum şu anda! Beni takıma almak ister misin?[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Dur bir saniye...[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Al benden de o kadar.[n][uf 1 1][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Nasıl hareket edeceğimi zihnimde canlandırabiliyorum. Katılmama izin verirsen pişman olmayacaksın.[n][uf 1 1][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pardon, çok affedersin.[n][uf 1 1][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Ah, aslında ben de benzer şeyler hissediyorum.[n][uf 1 1][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Şu an orada bilhassa işe yarayacağımı hissediyorum. Takıma beni de alır mısın?[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Bu ani gelebilir ama...[n][uf 1 1][e]

[msg MSG_064_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Benim için de aynı şey geçerli.[n][uf 1 1][e]

[msg MSG_064_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Acayip enerjiğim. Lütfen beni de ön cepheye al.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 1]-san, bir şey sormak istiyorum...[n][uf 1 1][e]

[msg MSG_065_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Aa, ben de![n][uf 1 1][e]

[msg MSG_065_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Beni de ön cepheye koyabilir misin? Şu an çok daha fazla güçlenebileceğimi hissediyorum.[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Hav![n][uf 1 1][e]

[msg MSG_066_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Sızlanır...[n][uf 1 1][e]

[msg MSG_066_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Hav! Hav! Hav![n][uf 1 1][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Hey, bekle bir saniye.[n][uf 1 1][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Araya girdiğim için üzgünüm ama aynen.[n][uf 1 1][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Beni de alabilir misin? Yani... Şu an epey iyiyim.[n][uf 1 1][e]

[msg MSG_064_7_0_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Gücüm artacakmış gibi hissediyorum. Beni de ön cepheye alır mısın?[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Aa, bu doğru... Sana söylemek istediğim bir şey var...[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Görünüşe göre Koro-chan'ın iki teürjisi var![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Başkan bunu, kendi potansiyelini araştırarak öğrendi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Neden böyle olduğunu tam olarak bilmiyoruz ama...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Bizim yanımızda olması güzel.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Takım oluştururken bunu aklında tut istersen. Hepsi bu![n][uf 1 1][e]

[msg MND_Tuto_MissingNPC_0]
[uf 0 5 65278][uf 2 1]Şimdi aklıma geldi de...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Elizabeth "misafirlerin"[n]Tartarus'a girdiğinden bahsetmişti...[n][uf 1 1][e]

