[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]L'ingresso del labirinto è in cima alle scale. Fai strada non appena ti senti pronto.[n][uf 1 1][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10089 0 0]Mentre esploriamo il Tartaro, questa sarà la nostra base operativa temporanea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10090 0 0]Affido a te le redini dell'operazione.[n][uf 1 1][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10091 0 0]Ne è passato di tempo da quando siamo venuti qui...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10092 0 0]È importante perfezionare qui le nostre abilità di combattimento, per essere pronti ad affrontate attacchi come quello di poco fa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10093 0 0]Non fa mai male allenarsi preventivamente. Non dimenticarlo.[n][uf 1 1][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10094 0 0]Spiegherò di nuovo alcune cose sul Tartaro in breve.[n][uf 1 1][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21001 0 0]Oh, [uf 4 1]-kun, la nuova spada non è niente male.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 1 21002 0 0]L'arco che ho io è leggero e sembra facile da usare. Non vedo l'ora di provarlo![n][uf 1 1][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 1 21003 0 0]Quindi il presidente ci ha dato armi nuove, eh? Forse è il caso di ringraziarlo.[n][uf 1 1][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 1 21004 0 0]Ma non ci ha spiegato quasi nulla. A volte non capisco se ci stia davvero aiutando o meno.[n][uf 1 1][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 21005 0 0]Ed è tutto fatto su misura per noi. Si capisce dalla scritta SEES incisa su ogni pezzo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 21006 0 0]Come al solito sei al comando, [uf 4 1]. E prima di partire non dimenticare di controllare l'equipaggiamento.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Ora che abbiamo Yamagishi, sarò disponibile anch'io in prima linea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Tuttavia, ritengo che dovremmo continuare a inviare in perlustrazione non più di quattro persone per volta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]La squadra sarebbe più coesa e terremmo saggiamente da parte dei membri di riserva in caso di sorprese.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Per quanto riguarda i membri da includere, lascio la scelta a te.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Una volta formato un gruppo coi membri qui disponibili, potrai partire quando vuoi.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Farò del mio meglio per aiutarvi tutti. Spero vada tutto bene![n][uf 1 1][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Uhm, non so esattamente cosa sto facendo, ma ce la metterò tutta![n][uf 1 1][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10105 0 0]Lo sapevo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10106 0 0]Quei dispositivi sono teletrasporti. Sono portali interconnessi tra loro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10107 0 0]Una volta attivati, si dovrebbe poter viaggiare verso tutti gli altri dispositivi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10108 0 0]Attiva tutti quelli che trovi. Saranno molto utili nelle prossime spedizioni.[n][uf 1 1][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bentornato! È proprio come pensavo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Quei dispositivi sono teletrasporti. Sono portali interconnessi tra loro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Una volta attivati, si dovrebbe poter viaggiare verso tutti gli altri dispositivi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ti conviene attivare tutti quelli che trovi. Saranno molto utili nelle prossime spedizioni.[n][uf 1 1][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Quella porta... sembra condurre a un percorso secondario del Tartaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]In sostanza, se punti ad arrivare in cima, prendere quella strada risulterebbe in una deviazione.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Tuttavia, seguendola, credo che potresti trovare qualcosa di molto utile per l'esplorazione...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]In base alla tua preparazione, oltrepassare queste porte potrebbe essere una buona idea.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Bentornato! Sei riuscito a salvare una persona scomparsa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Per adesso la faremo restare qui... la riporteremo indietro sana e salva al momento giusto.[n][uf 1 1][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]未使用[n][uf 1 1][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bentornato! Sono felice che tu sia riuscito a salvare quel gattino![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Per adesso può restare qui... lo riporteremo sano e salvo al momento giusto.[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], potresti concedermi un momento?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A quanto sembra, oggi nel Tartaro c'è qualcuno di speciale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Tra le fauci tiene stretto un frammento che emette una curiosa luce blu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Se la tua curiosità dovesse prendere il sopravvento, fai visita a quest'ospite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Ritengo che si trovi al piano [uf 2 4 0]. Beh, allora vai...[n][uf 1 1][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13216 0 0][uf 4 2], potresti concedermi un momento?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]A quanto sembra, oggi nel Tartaro c'è qualcuno di speciale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Che delizia rara ti attende... Se la tua curiosità dovesse prendere il sopravvento, fai visita a quest'ospite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Nel tuo futuro, magari ci saranno altri di questi curiosi frammenti brillanti![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Ritengo che si trovino ai piani [uf 2 4 0] e [uf 2 4 1]. Beh, allora vai...[n][uf 1 1][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13221 0 0]Oh? Ma tu pensa, che abbiamo qui?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Al momento, sembra che possiedi un gran numero di Personae.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Davvero notevole, oserei dire. Tuttavia...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Forse, nelle tue condizioni attuali, saresti in grado di utilizzare Personae ancora più potenti?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0]Qualora fossi interessato, presentati alla Stanza di Velluto.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4017 0 0]Ah, siete tornati. Bene, la sicurezza del gruppo è più importante di tutto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ho gli oggetti trovati dagli altri compagni di squadra durante l'operazione...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lascia che te li dia.[n][uf 1 1][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4075 0 0]Dunque, sta a te, il nostro leader, scegliere quando tornare, ma...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0]È maleducato lasciare indietro i propri compagni. Più tardi dovrai dare loro una spiegazione.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bentornato. Sono contenta che stiate tutti bene.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ho con me gli oggetti trovati da tutti gli altri durante questa uscita...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ora te li consegno.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]Ehm, so che probabilmente per loro non è un problema, ma quando gli altri vanno in perlustrazione...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Non è bello rientrare senza avvisarli... Io mi sentirei messa da parte se mi succedesse.[n][uf 1 1][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, prima che mi dimentichi, se stai tornando a esplorare...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Lascia che ti dia quello che hanno trovato tutti gli altri durante questa uscita.[n][uf 1 1][e]

[msg MND_CARD_INFO_01]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] sta reagendo...[n][uf 1 1][e]

[msg PFM_CARD_INFO_PRIESTESS]
[uf 0 5 65278][uf 2 1]La carta dell'Arcano maggiore Papessa[n]è stata aggiunta alla Mano arcana.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HERMIT]
[uf 0 5 65278][uf 2 1]La carta dell'Arcano maggiore Eremita[n]è stata aggiunta alla Mano arcana.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[uf 0 5 65278][uf 2 1]La carta dell'Arcano maggiore Appeso[n]è stata aggiunta alla Mano arcana.[n][uf 1 1][e]

[msg MND_CARD_INFO_02]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] e [uf 4 4 1 0 1 1] stanno reagendo...[n][uf 1 1][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[uf 0 5 65278][uf 2 1]Le carte degli Arcani maggiori Imperatrice e Imperatore[n]sono state aggiunte alla Mano arcana.[n][uf 1 1][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[uf 0 5 65278][uf 2 1]Le carte degli Arcani maggiori Ierofante e Amanti[n]sono state aggiunte alla Mano arcana.[n][uf 1 1][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[uf 0 5 65278][uf 2 1]Le carte degli Arcani maggiori Carro e Giustizia[n]sono state aggiunte alla Mano arcana.[n][uf 1 1][e]

[msg PFM_CARD_INFO_FORT_STREN]
[uf 0 5 65278][uf 2 1]Le carte degli Arcani maggiori Fortuna e Forza[n]sono state aggiunte alla Mano arcana.[n][uf 1 1][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[uf 0 5 65278][uf 2 1][uf 4 5 202 0 65535 65535 0 0][uf 3 1 3 0 65535 13202 0 0]Ti stavo aspettando. Potresti concedermi un attimo di tempo?[n][uf 1 1][e]

[msg MND_ArcanaInfo02]
[uf 0 5 65278][uf 2 1]La carta degli Amanti sta brillando...[n][uf 1 1][e]

[msg SYS_ArcanaInfo]
[uf 0 5 65278][uf 2 1]All'ottenimento degli Amanti,[n]il bonus dell'Affinità Sociale[n]durante la fusione aumenta.[n][uf 1 1][e]

[msg SYS_TutoAfter_TheurgiaGa]
[uf 0 5 65278][uf 2 1]È stato aggiunto il tutorial [uf 0 1 2]Teurgia[uf 0 1 27].[n][uf 1 1][e]

[msg SYS_TutoAfter_PartyMembe]
[uf 0 5 65278][uf 2 1]È stato aggiunto il tutorial [uf 0 1 2]Cambiare la formazione del gruppo[uf 0 1 27].[n][uf 1 1][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Ho provato a fare un'altra ricerca, ma non percepisco ancora la presenza di nessun altro dentro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Sembra che abbiamo salvato tutti quelli finiti per sbaglio nel Tartaro.[n][uf 1 1][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]State tutti bene?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Per un secondo vi ho perso tutti... ma poi è come se vi foste teletrasportati qui.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Che luogo bizzarro... A cosa pensi che serva quell'orologio?[n][uf 1 1][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[uf 0 5 65278][uf 2 1]Sembra essere utile...[e]
[uf 0 5 65278][uf 2 1]Non ne ho idea.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Se sembra essere utile, è meglio approfittarne.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Non sembra pericoloso... Anzi, magari ha un effetto positivo su tutti?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Proviamolo la prossima volta che si aprirà l'ingresso![n][uf 1 1][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Bentornato! Com'è andata con l'orologio stavolta?[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ehi, un secondo...[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oh, anch'io![n][uf 1 1][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Mi sento piuttosto bene al momento. Se non ti spiace, vorrei unirmi.[n][uf 1 1][e]

[msg MSG_060_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Ehi, [uf 4 2]...[n][uf 1 1][e]

[msg MSG_060_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Anch'io, anch'io![n][uf 1 1][e]

[msg MSG_060_7_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Mi sento pieno d'energia al momento, ti va di includermi nel gruppo?[n][uf 1 1][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Un momento...[n][uf 1 1][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ah, concordo.[n][uf 1 1][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ho un'immagine chiara di come dovrei muovermi: lasciami venire con te e non te ne pentirai.[n][uf 1 1][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pardon, chiedo scusa...[n][uf 1 1][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Oh... Mi sento anch'io così.[n][uf 1 1][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Sento che me la caverò particolarmente bene stavolta. Vorresti includermi nel gruppo?[n][uf 1 1][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]So che è un po' improvviso, ma...[n][uf 1 1][e]

[msg MSG_064_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Vale anche per me.[n][uf 1 1][e]

[msg MSG_064_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Mi sento insolitamente carica d'energia, ti invito a mettermi in prima linea.[n][uf 1 1][e]

[msg MSG_065_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 1]-san, vorrei chiederti...[n][uf 1 1][e]

[msg MSG_065_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Oh, anch'io![n][uf 1 1][e]

[msg MSG_065_7_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Potresti mettermi in prima linea? Sento che diventerò molto più forte adesso.[n][uf 1 1][e]

[msg MSG_066_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Bau![n][uf 1 1][e]

[msg MSG_066_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]*caììì*[n][uf 1 1][e]

[msg MSG_066_7_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Bau, bau! Bau![n][uf 1 1][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Ehi, aspetta un attimo.[n][uf 1 1][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Scusa se scoccio, ma, idem.[n][uf 1 1][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Puoi includermi? Insomma, mi sento benissimo al momento.[n][uf 1 1][e]

[msg MSG_064_7_0_H [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Sento che il mio potere si amplificherà. Potresti mettermi in prima linea?[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Ah, giusto. Volevo dirti una cosa...[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Sembra che Koro-chan abbia due Teurgie![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Il presidente l'ha imparato facendo ricerche sul suo potenziale.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Non siamo del tutto certi del perché sia così, ma...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Di sicuro è bello averlo dalla nostra parte.[n][uf 1 1][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Per cui, tienilo a mente mentre formi un gruppo. Tutto qui![n][uf 1 1][e]

[msg MND_Tuto_MissingNPC_0]
[uf 0 5 65278][uf 2 1]Ora che ci penso...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Elizabeth ha parlato di "ospiti"[n]vaganti per il Tartaro...[n][uf 1 1][e]

